package common

const (
	DbTemplateFuncName = "TemplateName"

	DBAutoGeneratedSqlOFFSET     = "_pageOffset"
	DBAutoGeneratedSqlPageSize   = "_pageSize"
	DBAutoGeneratedSqlPageOrigin = "_pageOrigin"
	DBAutoGeneratedSqlPageEnd    = "_pageEnd"
	DBAutoGeneratedSqlOrderBy    = "_orderBy"
	DBAutoGeneratedSqlPAGE       = "_page"
)

const (
	C1 = "/"
)
